name: Giphy PR Comment
description: A GitHub Action that comments a random Giphy on a PR
author: arsen
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  giphy-api-key:
    description: 'Giphy API key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.giphy_api_key }}