on:
  pull_request:
    types: [opened]

jobs:
    testing-action:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          issues: write
          pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Post comment with Giphy
              uses: ./  # Use the action in the root of the repository
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                giphy_api_key: ${{ secrets.GIPHY_API_KEY }}